# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
        environment:
          TZ: "/usr/share/zoneinfo/America/Los_Angeles"
          JVM_OPTS: -Xmx512m -Xms512m
