# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/elasticsearch

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx512m -Xms512m
